### ISSUE TITLE
Some fixes which needs to be done

### ISSUE THREAD

**Issue by Anish-Shobith** [developer-hole/Tesseract#4]
More default permissions could be added in here : https://github.com/developer-hole/Tesseract/blob/master/src/lib/structures/Command.js#L28

Probably await in here in order to catch errors : https://github.com/developer-hole/Tesseract/blob/master/src/events/commandHandler.js#L64

**Comment by officialpiyush** [comment]
* https://github.com/developer-hole/Tesseract/blob/master/src/lib/structures/Command.js#L28 - They are the basic permissions needed for a bot to work. There can be some commands which wouldn't require some perms which we specify there, causing command to fail. We can anytime add them in the extended Command class.

* https://github.com/developer-hole/Tesseract/blob/master/src/events/commandHandler.js#L64 - I don't think it will matter tbh. Looks okay to me and that try catch block would catch the errors even if wr don't await it afaik.


So overall I think this issue should be closed. If any of you ( literally anyone ) think I did something wrong or I misunderstood something, please Reopen the issue!!
